container:
  image: node:latest

check_task:
  env:
    CODECOV_TOKEN: b168afa5-aade-4992-9063-8840f4275862

  node_modules_cache:
    folder: node_modules
    fingerprint_script: cat package-lock.json
    populate_script: npm install

  lint_script: npm run lint

  test_script: npm run test && bash <(curl -s https://codecov.io/bash)

  build_script: npm run build
